version: "3.6"

services:
  parking_db:
    build:
      context: ./parking/up
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  parking:
    build:
      context: .
      dockerfile: ./parking/app.dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - parking_db
    environment:
      DATABASE_URL: postgres://parking:123456@parking_db/parking?sslmode=disable
    restart: on-failure
