version: "3.6"

services:
  db:
    build:
      context: ./parking/up
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: parking_test
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  parking:
    build:
      context: .
      dockerfile: ./parking/app.dockerfile.test
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://parking:123456@db/parking_test?sslmode=disable
    restart: on-failure
