version: "3.6"

services:
  db_test:
    build:
      context: ./parking/up
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: parking_test
      POSTGRES_USER: parking_test
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  parking:
    build:
      context: .
      dockerfile: ./parking/app.dockerfile.test
    ports:
      - "3568:8080"
    depends_on:
      - db_test
    environment:
      DATABASE_URL: postgres://parking_test:123456@db_test/parking_test?sslmode=disable
    restart: on-failure
