// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parking.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Park struct {
	SlotNum              uint32   `protobuf:"varint,1,opt,name=SlotNum,proto3" json:"SlotNum,omitempty"`
	CarReg               string   `protobuf:"bytes,2,opt,name=CarReg,proto3" json:"CarReg,omitempty"`
	CarColour            string   `protobuf:"bytes,3,opt,name=CarColour,proto3" json:"CarColour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Park) Reset()         { *m = Park{} }
func (m *Park) String() string { return proto.CompactTextString(m) }
func (*Park) ProtoMessage()    {}
func (*Park) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{0}
}
func (m *Park) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Park.Unmarshal(m, b)
}
func (m *Park) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Park.Marshal(b, m, deterministic)
}
func (dst *Park) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Park.Merge(dst, src)
}
func (m *Park) XXX_Size() int {
	return xxx_messageInfo_Park.Size(m)
}
func (m *Park) XXX_DiscardUnknown() {
	xxx_messageInfo_Park.DiscardUnknown(m)
}

var xxx_messageInfo_Park proto.InternalMessageInfo

func (m *Park) GetSlotNum() uint32 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

func (m *Park) GetCarReg() string {
	if m != nil {
		return m.CarReg
	}
	return ""
}

func (m *Park) GetCarColour() string {
	if m != nil {
		return m.CarColour
	}
	return ""
}

type Slot struct {
	SlotNum              uint32   `protobuf:"varint,1,opt,name=SlotNum,proto3" json:"SlotNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{1}
}
func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (dst *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(dst, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetSlotNum() uint32 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

type Car struct {
	CarReg               string   `protobuf:"bytes,1,opt,name=CarReg,proto3" json:"CarReg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{2}
}
func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (dst *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(dst, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetCarReg() string {
	if m != nil {
		return m.CarReg
	}
	return ""
}

type CreateLotRequest struct {
	MaxSlotsCount        uint32   `protobuf:"varint,1,opt,name=MaxSlotsCount,proto3" json:"MaxSlotsCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLotRequest) Reset()         { *m = CreateLotRequest{} }
func (m *CreateLotRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLotRequest) ProtoMessage()    {}
func (*CreateLotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{3}
}
func (m *CreateLotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLotRequest.Unmarshal(m, b)
}
func (m *CreateLotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLotRequest.Marshal(b, m, deterministic)
}
func (dst *CreateLotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLotRequest.Merge(dst, src)
}
func (m *CreateLotRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLotRequest.Size(m)
}
func (m *CreateLotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLotRequest proto.InternalMessageInfo

func (m *CreateLotRequest) GetMaxSlotsCount() uint32 {
	if m != nil {
		return m.MaxSlotsCount
	}
	return 0
}

type CreateLotResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLotResponse) Reset()         { *m = CreateLotResponse{} }
func (m *CreateLotResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLotResponse) ProtoMessage()    {}
func (*CreateLotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{4}
}
func (m *CreateLotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLotResponse.Unmarshal(m, b)
}
func (m *CreateLotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLotResponse.Marshal(b, m, deterministic)
}
func (dst *CreateLotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLotResponse.Merge(dst, src)
}
func (m *CreateLotResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLotResponse.Size(m)
}
func (m *CreateLotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLotResponse proto.InternalMessageInfo

func (m *CreateLotResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PostParkRequest struct {
	CarReg               string   `protobuf:"bytes,1,opt,name=CarReg,proto3" json:"CarReg,omitempty"`
	CarColour            string   `protobuf:"bytes,2,opt,name=CarColour,proto3" json:"CarColour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostParkRequest) Reset()         { *m = PostParkRequest{} }
func (m *PostParkRequest) String() string { return proto.CompactTextString(m) }
func (*PostParkRequest) ProtoMessage()    {}
func (*PostParkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{5}
}
func (m *PostParkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostParkRequest.Unmarshal(m, b)
}
func (m *PostParkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostParkRequest.Marshal(b, m, deterministic)
}
func (dst *PostParkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostParkRequest.Merge(dst, src)
}
func (m *PostParkRequest) XXX_Size() int {
	return xxx_messageInfo_PostParkRequest.Size(m)
}
func (m *PostParkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostParkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostParkRequest proto.InternalMessageInfo

func (m *PostParkRequest) GetCarReg() string {
	if m != nil {
		return m.CarReg
	}
	return ""
}

func (m *PostParkRequest) GetCarColour() string {
	if m != nil {
		return m.CarColour
	}
	return ""
}

type PostParkResponse struct {
	Park                 *Park    `protobuf:"bytes,1,opt,name=Park,proto3" json:"Park,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostParkResponse) Reset()         { *m = PostParkResponse{} }
func (m *PostParkResponse) String() string { return proto.CompactTextString(m) }
func (*PostParkResponse) ProtoMessage()    {}
func (*PostParkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{6}
}
func (m *PostParkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostParkResponse.Unmarshal(m, b)
}
func (m *PostParkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostParkResponse.Marshal(b, m, deterministic)
}
func (dst *PostParkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostParkResponse.Merge(dst, src)
}
func (m *PostParkResponse) XXX_Size() int {
	return xxx_messageInfo_PostParkResponse.Size(m)
}
func (m *PostParkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostParkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostParkResponse proto.InternalMessageInfo

func (m *PostParkResponse) GetPark() *Park {
	if m != nil {
		return m.Park
	}
	return nil
}

type PostUnparkRequest struct {
	SlotNum              uint32   `protobuf:"varint,1,opt,name=SlotNum,proto3" json:"SlotNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUnparkRequest) Reset()         { *m = PostUnparkRequest{} }
func (m *PostUnparkRequest) String() string { return proto.CompactTextString(m) }
func (*PostUnparkRequest) ProtoMessage()    {}
func (*PostUnparkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{7}
}
func (m *PostUnparkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUnparkRequest.Unmarshal(m, b)
}
func (m *PostUnparkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUnparkRequest.Marshal(b, m, deterministic)
}
func (dst *PostUnparkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUnparkRequest.Merge(dst, src)
}
func (m *PostUnparkRequest) XXX_Size() int {
	return xxx_messageInfo_PostUnparkRequest.Size(m)
}
func (m *PostUnparkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUnparkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostUnparkRequest proto.InternalMessageInfo

func (m *PostUnparkRequest) GetSlotNum() uint32 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

type PostUnparkResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUnparkResponse) Reset()         { *m = PostUnparkResponse{} }
func (m *PostUnparkResponse) String() string { return proto.CompactTextString(m) }
func (*PostUnparkResponse) ProtoMessage()    {}
func (*PostUnparkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{8}
}
func (m *PostUnparkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUnparkResponse.Unmarshal(m, b)
}
func (m *PostUnparkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUnparkResponse.Marshal(b, m, deterministic)
}
func (dst *PostUnparkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUnparkResponse.Merge(dst, src)
}
func (m *PostUnparkResponse) XXX_Size() int {
	return xxx_messageInfo_PostUnparkResponse.Size(m)
}
func (m *PostUnparkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUnparkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostUnparkResponse proto.InternalMessageInfo

func (m *PostUnparkResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetParksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParksRequest) Reset()         { *m = GetParksRequest{} }
func (m *GetParksRequest) String() string { return proto.CompactTextString(m) }
func (*GetParksRequest) ProtoMessage()    {}
func (*GetParksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{9}
}
func (m *GetParksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParksRequest.Unmarshal(m, b)
}
func (m *GetParksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParksRequest.Marshal(b, m, deterministic)
}
func (dst *GetParksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParksRequest.Merge(dst, src)
}
func (m *GetParksRequest) XXX_Size() int {
	return xxx_messageInfo_GetParksRequest.Size(m)
}
func (m *GetParksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetParksRequest proto.InternalMessageInfo

type GetParksResponse struct {
	Parks                []*Park  `protobuf:"bytes,1,rep,name=Parks,proto3" json:"Parks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParksResponse) Reset()         { *m = GetParksResponse{} }
func (m *GetParksResponse) String() string { return proto.CompactTextString(m) }
func (*GetParksResponse) ProtoMessage()    {}
func (*GetParksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{10}
}
func (m *GetParksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParksResponse.Unmarshal(m, b)
}
func (m *GetParksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParksResponse.Marshal(b, m, deterministic)
}
func (dst *GetParksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParksResponse.Merge(dst, src)
}
func (m *GetParksResponse) XXX_Size() int {
	return xxx_messageInfo_GetParksResponse.Size(m)
}
func (m *GetParksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetParksResponse proto.InternalMessageInfo

func (m *GetParksResponse) GetParks() []*Park {
	if m != nil {
		return m.Parks
	}
	return nil
}

type GetCarRegsByColourRequest struct {
	CarColour            string   `protobuf:"bytes,1,opt,name=CarColour,proto3" json:"CarColour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarRegsByColourRequest) Reset()         { *m = GetCarRegsByColourRequest{} }
func (m *GetCarRegsByColourRequest) String() string { return proto.CompactTextString(m) }
func (*GetCarRegsByColourRequest) ProtoMessage()    {}
func (*GetCarRegsByColourRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{11}
}
func (m *GetCarRegsByColourRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarRegsByColourRequest.Unmarshal(m, b)
}
func (m *GetCarRegsByColourRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarRegsByColourRequest.Marshal(b, m, deterministic)
}
func (dst *GetCarRegsByColourRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarRegsByColourRequest.Merge(dst, src)
}
func (m *GetCarRegsByColourRequest) XXX_Size() int {
	return xxx_messageInfo_GetCarRegsByColourRequest.Size(m)
}
func (m *GetCarRegsByColourRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarRegsByColourRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarRegsByColourRequest proto.InternalMessageInfo

func (m *GetCarRegsByColourRequest) GetCarColour() string {
	if m != nil {
		return m.CarColour
	}
	return ""
}

type GetCarRegsByColourResponse struct {
	Cars                 []string `protobuf:"bytes,1,rep,name=Cars,proto3" json:"Cars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarRegsByColourResponse) Reset()         { *m = GetCarRegsByColourResponse{} }
func (m *GetCarRegsByColourResponse) String() string { return proto.CompactTextString(m) }
func (*GetCarRegsByColourResponse) ProtoMessage()    {}
func (*GetCarRegsByColourResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{12}
}
func (m *GetCarRegsByColourResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarRegsByColourResponse.Unmarshal(m, b)
}
func (m *GetCarRegsByColourResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarRegsByColourResponse.Marshal(b, m, deterministic)
}
func (dst *GetCarRegsByColourResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarRegsByColourResponse.Merge(dst, src)
}
func (m *GetCarRegsByColourResponse) XXX_Size() int {
	return xxx_messageInfo_GetCarRegsByColourResponse.Size(m)
}
func (m *GetCarRegsByColourResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarRegsByColourResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarRegsByColourResponse proto.InternalMessageInfo

func (m *GetCarRegsByColourResponse) GetCars() []string {
	if m != nil {
		return m.Cars
	}
	return nil
}

type GetSlotsByColourRequest struct {
	CarColour            string   `protobuf:"bytes,1,opt,name=CarColour,proto3" json:"CarColour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotsByColourRequest) Reset()         { *m = GetSlotsByColourRequest{} }
func (m *GetSlotsByColourRequest) String() string { return proto.CompactTextString(m) }
func (*GetSlotsByColourRequest) ProtoMessage()    {}
func (*GetSlotsByColourRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{13}
}
func (m *GetSlotsByColourRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotsByColourRequest.Unmarshal(m, b)
}
func (m *GetSlotsByColourRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotsByColourRequest.Marshal(b, m, deterministic)
}
func (dst *GetSlotsByColourRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotsByColourRequest.Merge(dst, src)
}
func (m *GetSlotsByColourRequest) XXX_Size() int {
	return xxx_messageInfo_GetSlotsByColourRequest.Size(m)
}
func (m *GetSlotsByColourRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotsByColourRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotsByColourRequest proto.InternalMessageInfo

func (m *GetSlotsByColourRequest) GetCarColour() string {
	if m != nil {
		return m.CarColour
	}
	return ""
}

type GetSlotsByColourResponse struct {
	Slots                []uint32 `protobuf:"varint,1,rep,packed,name=Slots,proto3" json:"Slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotsByColourResponse) Reset()         { *m = GetSlotsByColourResponse{} }
func (m *GetSlotsByColourResponse) String() string { return proto.CompactTextString(m) }
func (*GetSlotsByColourResponse) ProtoMessage()    {}
func (*GetSlotsByColourResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{14}
}
func (m *GetSlotsByColourResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotsByColourResponse.Unmarshal(m, b)
}
func (m *GetSlotsByColourResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotsByColourResponse.Marshal(b, m, deterministic)
}
func (dst *GetSlotsByColourResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotsByColourResponse.Merge(dst, src)
}
func (m *GetSlotsByColourResponse) XXX_Size() int {
	return xxx_messageInfo_GetSlotsByColourResponse.Size(m)
}
func (m *GetSlotsByColourResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotsByColourResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotsByColourResponse proto.InternalMessageInfo

func (m *GetSlotsByColourResponse) GetSlots() []uint32 {
	if m != nil {
		return m.Slots
	}
	return nil
}

type GetSlotByCarRegRequest struct {
	CarReg               string   `protobuf:"bytes,1,opt,name=CarReg,proto3" json:"CarReg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotByCarRegRequest) Reset()         { *m = GetSlotByCarRegRequest{} }
func (m *GetSlotByCarRegRequest) String() string { return proto.CompactTextString(m) }
func (*GetSlotByCarRegRequest) ProtoMessage()    {}
func (*GetSlotByCarRegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{15}
}
func (m *GetSlotByCarRegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotByCarRegRequest.Unmarshal(m, b)
}
func (m *GetSlotByCarRegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotByCarRegRequest.Marshal(b, m, deterministic)
}
func (dst *GetSlotByCarRegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotByCarRegRequest.Merge(dst, src)
}
func (m *GetSlotByCarRegRequest) XXX_Size() int {
	return xxx_messageInfo_GetSlotByCarRegRequest.Size(m)
}
func (m *GetSlotByCarRegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotByCarRegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotByCarRegRequest proto.InternalMessageInfo

func (m *GetSlotByCarRegRequest) GetCarReg() string {
	if m != nil {
		return m.CarReg
	}
	return ""
}

type GetSlotByCarRegResponse struct {
	SlotNum              uint32   `protobuf:"varint,1,opt,name=SlotNum,proto3" json:"SlotNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSlotByCarRegResponse) Reset()         { *m = GetSlotByCarRegResponse{} }
func (m *GetSlotByCarRegResponse) String() string { return proto.CompactTextString(m) }
func (*GetSlotByCarRegResponse) ProtoMessage()    {}
func (*GetSlotByCarRegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parking_eb458f0160defcc0, []int{16}
}
func (m *GetSlotByCarRegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSlotByCarRegResponse.Unmarshal(m, b)
}
func (m *GetSlotByCarRegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSlotByCarRegResponse.Marshal(b, m, deterministic)
}
func (dst *GetSlotByCarRegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSlotByCarRegResponse.Merge(dst, src)
}
func (m *GetSlotByCarRegResponse) XXX_Size() int {
	return xxx_messageInfo_GetSlotByCarRegResponse.Size(m)
}
func (m *GetSlotByCarRegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSlotByCarRegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSlotByCarRegResponse proto.InternalMessageInfo

func (m *GetSlotByCarRegResponse) GetSlotNum() uint32 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

func init() {
	proto.RegisterType((*Park)(nil), "protobuf.Park")
	proto.RegisterType((*Slot)(nil), "protobuf.Slot")
	proto.RegisterType((*Car)(nil), "protobuf.Car")
	proto.RegisterType((*CreateLotRequest)(nil), "protobuf.CreateLotRequest")
	proto.RegisterType((*CreateLotResponse)(nil), "protobuf.CreateLotResponse")
	proto.RegisterType((*PostParkRequest)(nil), "protobuf.PostParkRequest")
	proto.RegisterType((*PostParkResponse)(nil), "protobuf.PostParkResponse")
	proto.RegisterType((*PostUnparkRequest)(nil), "protobuf.PostUnparkRequest")
	proto.RegisterType((*PostUnparkResponse)(nil), "protobuf.PostUnparkResponse")
	proto.RegisterType((*GetParksRequest)(nil), "protobuf.GetParksRequest")
	proto.RegisterType((*GetParksResponse)(nil), "protobuf.GetParksResponse")
	proto.RegisterType((*GetCarRegsByColourRequest)(nil), "protobuf.GetCarRegsByColourRequest")
	proto.RegisterType((*GetCarRegsByColourResponse)(nil), "protobuf.GetCarRegsByColourResponse")
	proto.RegisterType((*GetSlotsByColourRequest)(nil), "protobuf.GetSlotsByColourRequest")
	proto.RegisterType((*GetSlotsByColourResponse)(nil), "protobuf.GetSlotsByColourResponse")
	proto.RegisterType((*GetSlotByCarRegRequest)(nil), "protobuf.GetSlotByCarRegRequest")
	proto.RegisterType((*GetSlotByCarRegResponse)(nil), "protobuf.GetSlotByCarRegResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ParkingServiceClient is the client API for ParkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParkingServiceClient interface {
	CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotResponse, error)
	PostPark(ctx context.Context, in *PostParkRequest, opts ...grpc.CallOption) (*PostParkResponse, error)
	PostUnpark(ctx context.Context, in *PostUnparkRequest, opts ...grpc.CallOption) (*PostUnparkResponse, error)
	GetParks(ctx context.Context, in *GetParksRequest, opts ...grpc.CallOption) (*GetParksResponse, error)
	GetCarRegsByColour(ctx context.Context, in *GetCarRegsByColourRequest, opts ...grpc.CallOption) (*GetCarRegsByColourResponse, error)
	GetSlotsByColour(ctx context.Context, in *GetSlotsByColourRequest, opts ...grpc.CallOption) (*GetSlotsByColourResponse, error)
	GetSlotByCarReg(ctx context.Context, in *GetSlotByCarRegRequest, opts ...grpc.CallOption) (*GetSlotByCarRegResponse, error)
}

type parkingServiceClient struct {
	cc *grpc.ClientConn
}

func NewParkingServiceClient(cc *grpc.ClientConn) ParkingServiceClient {
	return &parkingServiceClient{cc}
}

func (c *parkingServiceClient) CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotResponse, error) {
	out := new(CreateLotResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/CreateLot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) PostPark(ctx context.Context, in *PostParkRequest, opts ...grpc.CallOption) (*PostParkResponse, error) {
	out := new(PostParkResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/PostPark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) PostUnpark(ctx context.Context, in *PostUnparkRequest, opts ...grpc.CallOption) (*PostUnparkResponse, error) {
	out := new(PostUnparkResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/PostUnpark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetParks(ctx context.Context, in *GetParksRequest, opts ...grpc.CallOption) (*GetParksResponse, error) {
	out := new(GetParksResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/GetParks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetCarRegsByColour(ctx context.Context, in *GetCarRegsByColourRequest, opts ...grpc.CallOption) (*GetCarRegsByColourResponse, error) {
	out := new(GetCarRegsByColourResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/GetCarRegsByColour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetSlotsByColour(ctx context.Context, in *GetSlotsByColourRequest, opts ...grpc.CallOption) (*GetSlotsByColourResponse, error) {
	out := new(GetSlotsByColourResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/GetSlotsByColour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetSlotByCarReg(ctx context.Context, in *GetSlotByCarRegRequest, opts ...grpc.CallOption) (*GetSlotByCarRegResponse, error) {
	out := new(GetSlotByCarRegResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ParkingService/GetSlotByCarReg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServiceServer is the server API for ParkingService service.
type ParkingServiceServer interface {
	CreateLot(context.Context, *CreateLotRequest) (*CreateLotResponse, error)
	PostPark(context.Context, *PostParkRequest) (*PostParkResponse, error)
	PostUnpark(context.Context, *PostUnparkRequest) (*PostUnparkResponse, error)
	GetParks(context.Context, *GetParksRequest) (*GetParksResponse, error)
	GetCarRegsByColour(context.Context, *GetCarRegsByColourRequest) (*GetCarRegsByColourResponse, error)
	GetSlotsByColour(context.Context, *GetSlotsByColourRequest) (*GetSlotsByColourResponse, error)
	GetSlotByCarReg(context.Context, *GetSlotByCarRegRequest) (*GetSlotByCarRegResponse, error)
}

func RegisterParkingServiceServer(s *grpc.Server, srv ParkingServiceServer) {
	s.RegisterService(&_ParkingService_serviceDesc, srv)
}

func _ParkingService_CreateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/CreateLot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateLot(ctx, req.(*CreateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_PostPark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostParkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).PostPark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/PostPark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).PostPark(ctx, req.(*PostParkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_PostUnpark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUnparkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).PostUnpark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/PostUnpark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).PostUnpark(ctx, req.(*PostUnparkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetParks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetParks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/GetParks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetParks(ctx, req.(*GetParksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetCarRegsByColour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarRegsByColourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetCarRegsByColour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/GetCarRegsByColour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetCarRegsByColour(ctx, req.(*GetCarRegsByColourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetSlotsByColour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotsByColourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetSlotsByColour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/GetSlotsByColour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetSlotsByColour(ctx, req.(*GetSlotsByColourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetSlotByCarReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotByCarRegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetSlotByCarReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ParkingService/GetSlotByCarReg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetSlotByCarReg(ctx, req.(*GetSlotByCarRegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParkingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ParkingService",
	HandlerType: (*ParkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLot",
			Handler:    _ParkingService_CreateLot_Handler,
		},
		{
			MethodName: "PostPark",
			Handler:    _ParkingService_PostPark_Handler,
		},
		{
			MethodName: "PostUnpark",
			Handler:    _ParkingService_PostUnpark_Handler,
		},
		{
			MethodName: "GetParks",
			Handler:    _ParkingService_GetParks_Handler,
		},
		{
			MethodName: "GetCarRegsByColour",
			Handler:    _ParkingService_GetCarRegsByColour_Handler,
		},
		{
			MethodName: "GetSlotsByColour",
			Handler:    _ParkingService_GetSlotsByColour_Handler,
		},
		{
			MethodName: "GetSlotByCarReg",
			Handler:    _ParkingService_GetSlotByCarReg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parking.proto",
}

func init() { proto.RegisterFile("parking.proto", fileDescriptor_parking_eb458f0160defcc0) }

var fileDescriptor_parking_eb458f0160defcc0 = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x4e, 0xdb, 0x4e,
	0x10, 0x96, 0xf9, 0xf7, 0x23, 0xf3, 0x53, 0x80, 0x8c, 0x5a, 0x30, 0x26, 0x54, 0x61, 0x09, 0x2a,
	0x2a, 0x85, 0x50, 0x90, 0xfa, 0xef, 0x88, 0x0f, 0xb9, 0xb4, 0x15, 0x32, 0x6a, 0x2f, 0x95, 0x2a,
	0x2d, 0xd1, 0x62, 0x45, 0xa4, 0xde, 0x74, 0x77, 0x8d, 0x8a, 0x5a, 0x2e, 0x3d, 0xf4, 0xd8, 0x4b,
	0x9f, 0xa4, 0xcf, 0xd2, 0x57, 0xe8, 0x83, 0x54, 0x1e, 0xaf, 0x13, 0xdb, 0x38, 0x41, 0x3d, 0x25,
	0xbb, 0x33, 0xf3, 0x7d, 0xdf, 0xcc, 0x7e, 0x63, 0xa8, 0x0f, 0xb9, 0xba, 0xec, 0x47, 0xe1, 0xc1,
	0x50, 0x49, 0x23, 0x71, 0x91, 0x7e, 0xce, 0xe3, 0x0b, 0xaf, 0x19, 0x4a, 0x19, 0x0e, 0x44, 0x87,
	0x0f, 0xfb, 0x1d, 0x1e, 0x45, 0xd2, 0x70, 0xd3, 0x97, 0x91, 0x4e, 0xf3, 0xd8, 0x3b, 0x98, 0x3b,
	0xe5, 0xea, 0x12, 0x5d, 0xf8, 0xef, 0x6c, 0x20, 0xcd, 0x9b, 0xf8, 0xa3, 0xeb, 0xb4, 0x9c, 0xdd,
	0x7a, 0x90, 0x1d, 0x71, 0x15, 0x16, 0x7c, 0xae, 0x02, 0x11, 0xba, 0x33, 0x2d, 0x67, 0xb7, 0x16,
	0xd8, 0x13, 0x36, 0xa1, 0xe6, 0x73, 0xe5, 0xcb, 0x81, 0x8c, 0x95, 0x3b, 0x4b, 0xa1, 0xf1, 0x05,
	0x6b, 0xc1, 0x5c, 0x02, 0x30, 0x19, 0x97, 0x6d, 0xc2, 0xac, 0xcf, 0x55, 0x0e, 0xde, 0xc9, 0xc3,
	0xb3, 0xe7, 0xb0, 0xe2, 0x2b, 0xc1, 0x8d, 0x78, 0x25, 0x4d, 0x20, 0x3e, 0xc5, 0x42, 0x1b, 0x6c,
	0x43, 0xfd, 0x35, 0xff, 0x9c, 0x00, 0x68, 0x5f, 0xc6, 0x91, 0xb1, 0x90, 0xc5, 0x4b, 0xb6, 0x07,
	0x8d, 0x5c, 0xa5, 0x1e, 0xca, 0x48, 0x8b, 0x84, 0xe6, 0xcc, 0x70, 0x13, 0xeb, 0x8c, 0x26, 0x3d,
	0xb1, 0x2e, 0x2c, 0x9f, 0x4a, 0x6d, 0x92, 0x19, 0x64, 0x2c, 0x13, 0x14, 0x15, 0x1b, 0x9e, 0x29,
	0x37, 0xfc, 0x14, 0x56, 0xc6, 0x40, 0x96, 0x94, 0xa5, 0xc3, 0x25, 0x9c, 0xff, 0x8f, 0x96, 0x0e,
	0xb2, 0x37, 0x39, 0xa0, 0x2c, 0x8a, 0xb1, 0x7d, 0x68, 0x24, 0x75, 0x6f, 0xa3, 0x61, 0x4e, 0xc2,
	0xe4, 0xa9, 0x3d, 0x06, 0xcc, 0xa7, 0xdf, 0xd1, 0x5d, 0x03, 0x96, 0xbb, 0x82, 0x34, 0x69, 0x0b,
	0x9d, 0xcc, 0x75, 0x7c, 0x65, 0xcb, 0xdb, 0x30, 0x4f, 0x17, 0xae, 0xd3, 0x9a, 0xad, 0x10, 0x9a,
	0x06, 0xd9, 0x0b, 0x58, 0xef, 0x0a, 0x93, 0x0e, 0x43, 0x9f, 0x5c, 0xa7, 0x7d, 0x67, 0x8a, 0x0b,
	0xc3, 0x71, 0xca, 0xc3, 0x39, 0x04, 0xaf, 0xaa, 0xd4, 0xd2, 0x23, 0xcc, 0xf9, 0x5c, 0xa5, 0xec,
	0xb5, 0x80, 0xfe, 0xb3, 0x67, 0xb0, 0xd6, 0x15, 0x86, 0x5e, 0xf5, 0x5f, 0xa9, 0xdc, 0xdb, 0x85,
	0x96, 0xe8, 0x1e, 0xcc, 0x53, 0x80, 0x98, 0xea, 0x41, 0x7a, 0x60, 0x87, 0xb0, 0x6a, 0x2b, 0x4e,
	0xae, 0x53, 0x89, 0x77, 0x38, 0x81, 0x1d, 0x8f, 0xc4, 0x8d, 0x2b, 0x2c, 0xc5, 0xc4, 0x97, 0x3b,
	0xfa, 0xb5, 0x00, 0x4b, 0xa7, 0xe9, 0x8e, 0x9e, 0x09, 0x75, 0xd5, 0xef, 0x09, 0x3c, 0x87, 0xda,
	0xc8, 0xa9, 0xe8, 0x8d, 0xa7, 0x5e, 0x36, 0xbe, 0xb7, 0x51, 0x19, 0x4b, 0x29, 0x59, 0xf3, 0xdb,
	0xef, 0x3f, 0x3f, 0x67, 0x56, 0x59, 0x83, 0x56, 0xfc, 0xea, 0x49, 0xa7, 0x47, 0x29, 0x03, 0x69,
	0x5e, 0x3a, 0x8f, 0xf0, 0x03, 0x2c, 0x66, 0xbe, 0xc4, 0xf5, 0xdc, 0xc3, 0x16, 0x4d, 0xef, 0x79,
	0x55, 0x21, 0x4b, 0xb0, 0x41, 0x04, 0xf7, 0xd9, 0x4a, 0x46, 0x30, 0x94, 0xda, 0x24, 0xfe, 0x4b,
	0xf0, 0x2f, 0x00, 0xc6, 0x86, 0xc4, 0x8d, 0x22, 0x4c, 0xc1, 0xd5, 0x5e, 0xb3, 0x3a, 0x68, 0x59,
	0x36, 0x89, 0x65, 0x8d, 0x61, 0x9e, 0x25, 0x8e, 0x32, 0x9e, 0xf7, 0xb0, 0x98, 0xf9, 0x36, 0xdf,
	0x47, 0xc9, 0xde, 0xf9, 0x3e, 0xca, 0x36, 0x67, 0x2e, 0x31, 0x20, 0x8e, 0xfa, 0x08, 0x05, 0xb5,
	0xa1, 0xf1, 0x87, 0x03, 0x78, 0xdb, 0xa0, 0xb8, 0x5d, 0x00, 0xab, 0x76, 0xbe, 0xd7, 0x9e, 0x9e,
	0x64, 0xb9, 0xf7, 0x89, 0xfb, 0x21, 0xee, 0xe4, 0xb8, 0x7b, 0x5c, 0x29, 0x11, 0xea, 0x4e, 0x8f,
	0x52, 0x3b, 0x5f, 0x46, 0x26, 0xbe, 0xc1, 0xef, 0x0e, 0xad, 0x69, 0xc1, 0xc6, 0xb8, 0x55, 0x60,
	0xaa, 0xda, 0x0d, 0x8f, 0x4d, 0x4b, 0xb1, 0x52, 0xf6, 0x48, 0xca, 0x0e, 0x6e, 0xe7, 0xa4, 0xe8,
	0x24, 0xb3, 0x4a, 0xc8, 0x57, 0xfa, 0x82, 0xe4, 0xad, 0x8e, 0xad, 0x5b, 0x1c, 0xa5, 0xbd, 0xf1,
	0xb6, 0xa6, 0x64, 0x58, 0x11, 0x6d, 0x12, 0xf1, 0x00, 0x9b, 0x25, 0x11, 0x1d, 0x25, 0x42, 0x12,
	0x10, 0x88, 0xf0, 0xe6, 0x7c, 0x81, 0x70, 0x8e, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x03, 0x5e,
	0x3b, 0x92, 0xdd, 0x06, 0x00, 0x00,
}
